#!/bin/sh

if [ -f ./main.pdf ]; then
  echo "File 'main.pdf' exists, trying to copy it to gh-pages branch"
else
 exit 0
fi

cp ./main.pdf /delete_me.pdf
git checkout gh-pages
cp /delete_me.pdf ./main.pdf
rm -i /delete_me.pdf < y
git checkout master

exit 0
